import "./globals.css";
import ClientAppWrapper from "@/components/ClientWrapper";



export const metadata = {
  title: "jobPortal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
           <ClientAppWrapper>
               {children}
           </ClientAppWrapper>
      </body>
    </html>
  );
}

